### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by arpitbbhayani** [relogX/system-design-questions#1]

**Comment by arpitbbhayani** [comment]
![System Design Assignments](https://user-images.githubusercontent.com/4745789/137951051-3d18a202-e719-4e9c-a430-d8da6ddebaec.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(1)](https://user-images.githubusercontent.com/4745789/138017480-1f7c30ce-50f2-4a50-99b5-1cf7f0778caa.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(2)](https://user-images.githubusercontent.com/4745789/138110826-1490cac9-5a02-43bd-bb14-74334742dd16.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(3)](https://user-images.githubusercontent.com/4745789/138638518-f718d9e9-437e-4fef-93af-65b0f7024918.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(5)](https://user-images.githubusercontent.com/4745789/138721841-3fc02879-7075-491a-9dcf-74011dba11e6.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(6)](https://user-images.githubusercontent.com/4745789/138806145-0ad10712-26c4-4c21-aeed-eb2f28157959.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(7)](https://user-images.githubusercontent.com/4745789/139183521-43e7a5c8-a629-4f85-9584-21dd873d0ade.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(8)](https://user-images.githubusercontent.com/4745789/139275645-132ecb0a-0e39-476f-b95d-007dbac76a4e.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(9)](https://user-images.githubusercontent.com/4745789/139569887-2247a841-f78d-4546-a331-ec4d891f453a.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(10)](https://user-images.githubusercontent.com/4745789/139570503-5b213da5-3a74-4187-9843-c3f718abe0e4.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(11)](https://user-images.githubusercontent.com/4745789/139574973-6bd4202d-4256-44a1-bbbd-271f9c3b745b.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(12)](https://user-images.githubusercontent.com/4745789/139575791-ff4f4b01-f853-482f-9291-66731559da98.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(13)](https://user-images.githubusercontent.com/4745789/139584187-5ae0e08e-16eb-4354-9fa3-fc286a244887.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(14)](https://user-images.githubusercontent.com/4745789/139584929-5e00fd58-c731-4f91-aaa8-7383acd99ff4.png)

**Comment by arpitbbhayani** [comment]
![System Design Assignments(3)](https://user-images.githubusercontent.com/4745789/141650924-943da5ba-c3a0-4d86-b3f2-a300be7bea9d.png)

**Comment by arpitbbhayani** [comment]
![f9gUFy-9uCM](https://user-images.githubusercontent.com/4745789/233762596-5aba651e-ebe8-4b9c-9bd9-70d0dcd81e98.png)
Nice image. anhglinfa n

**Comment by Tushar11Varshney** [comment]
![WhatsApp Image 2022-11-15 at 21 08 08](https://github.com/arpitbbhayani/system-design-questions/assets/65900578/eabcc8d5-97cf-4f02-a59f-f42e02f8f6a1)

**Comment by Tushar11Varshney** [comment]
![Screenshot (195)](https://github.com/arpitbbhayani/system-design-questions/assets/65900578/ce9e9351-bf19-4791-b4e9-b8a569e5cef4)

**Comment by Tushar11Varshney** [comment]
![Screenshot (197)](https://github.com/arpitbbhayani/system-design-questions/assets/65900578/c1a496b7-1f14-4802-af4a-c5ef3556b41e)

**Comment by Tushar11Varshney** [comment]
![Screenshot (1728)](https://github.com/arpitbbhayani/system-design-questions/assets/65900578/7027cff0-4033-462e-aa53-d5d16a3189ea)

**Comment by arpitbbhayani** [comment]
![relog](https://github.com/arpitbbhayani/system-design-questions/assets/4745789/4d281068-e25a-4ef8-b47b-fa632f9c37c2)

**Comment by arpitbbhayani** [comment]
![Screenshot 2024-02-09 121434](https://github.com/arpitbbhayani/system-design-questions/assets/4745789/f1bef47c-6630-4309-b276-6112e1388643)

**Comment by arpitbbhayani** [comment]
![Screenshot 2024-02-09 121539](https://github.com/arpitbbhayani/system-design-questions/assets/4745789/abc5c535-5eeb-4c2c-bf35-0b15be971282)
